(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
let audioCtx=null,sfxEnabled=true,musicEnabled=true,musicGain=null,musicCompressor=null,musicTimer=null,musicStep=0,musicNextTime=0;
function ensureAudio(){if(!audioCtx){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return null;audioCtx=new AudioContext()}if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
const audioSamples={knockout:'assets/audio/knockout-bell.ogg'};
function playSample(name,volume=1){if(!sfxEnabled||!audioSamples[name])return;const sample=new Audio(audioSamples[name]);sample.volume=volume;sample.play().catch(()=>{})}
function pixelateOverdriveLetters(){if(!document.fonts||!document.fonts.load)return;document.fonts.load('38px Adrip').then(()=>{document.querySelectorAll('.overdrive-letter-flight>span').forEach(letter=>{if(letter.querySelector('canvas'))return;const glyph=letter.textContent.trim(),canvas=document.createElement('canvas'),probe=document.createElement('canvas').getContext('2d');probe.font='38px Adrip';const metrics=probe.measureText(glyph),pad=3,left=Math.ceil(metrics.actualBoundingBoxLeft||0),right=Math.ceil(metrics.actualBoundingBoxRight||metrics.width),ascent=Math.ceil(metrics.actualBoundingBoxAscent||38),descent=Math.ceil(metrics.actualBoundingBoxDescent||8);canvas.width=Math.max(8,left+right+pad*2);canvas.height=Math.max(12,ascent+descent+pad*2);const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.font='38px Adrip';ctx.fillStyle='#fff';ctx.textBaseline='alphabetic';ctx.fillText(glyph,pad+left,pad+ascent);canvas.setAttribute('aria-hidden','true');letter.textContent='';letter.appendChild(canvas)})}).catch(()=>{})}
function tone(freq,duration=.08,type='square',volume=.035,delay=0,slide=0){const ac=ensureAudio();if(!ac)return;const start=ac.currentTime+delay,o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,start);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),start+duration);g.gain.setValueAtTime(0,start);g.gain.linearRampToValueAtTime(volume,start+.006);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(g).connect(ac.destination);o.start(start);o.stop(start+duration+.02)}
function noise(duration=.12,volume=.025,delay=0,highpass=700){const ac=ensureAudio();if(!ac)return;const length=Math.ceil(ac.sampleRate*duration),buffer=ac.createBuffer(1,length,ac.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const source=ac.createBufferSource(),filter=ac.createBiquadFilter(),g=ac.createGain();source.buffer=buffer;filter.type='highpass';filter.frequency.value=highpass;const start=ac.currentTime+delay;g.gain.setValueAtTime(volume,start);g.gain.exponentialRampToValueAtTime(.0001,start+duration);source.connect(filter).connect(g).connect(ac.destination);source.start(start)}
function sfx(name){if(!sfxEnabled)return;switch(name){case'move':tone(150,.035,'square',.018,0,-18);break;case'rotate':tone(270,.055,'square',.025,0,110);tone(410,.035,'square',.014,.045);break;case'lock':tone(105,.07,'square',.035,0,-35);noise(.055,.015,0,350);break;case'hardDrop':tone(170,.11,'square',.04,0,-110);noise(.12,.027,0,250);break;case'line1':tone(330,.08,'square',.03);tone(440,.09,'square',.03,.075);break;case'line2':tone(330,.07,'square',.03);tone(494,.07,'square',.03,.06);tone(659,.13,'square',.035,.12);break;case'line3':tone(262,.07,'square',.035);tone(392,.07,'square',.035,.055);tone(523,.07,'square',.035,.11);tone(784,.18,'square',.04,.165);break;case'bomb':tone(90,.38,'sawtooth',.055,0,-55);noise(.48,.06,0,120);tone(45,.3,'square',.045,.08,-10);break;case'warning':tone(660,.09,'square',.027);tone(440,.09,'square',.027,.12);break;case'enemy':tone(125,.16,'sawtooth',.04,0,-55);noise(.18,.026,.04,500);break;case'hurt':tone(190,.18,'square',.04,0,-120);noise(.1,.022);break;case'emergency':for(let i=0;i<5;i++){tone(i%2?390:620,.12,'square',.045,i*.2);tone(i%2?780:310,.12,'square',.025,i*.2)}break;case'phase':tone(110,.45,'sawtooth',.045,0,330);tone(220,.35,'square',.03,.22,440);break;case'impossible':tone(294,.09,'square',.03);tone(466,.1,'square',.03,.07);tone(698,.16,'square',.035,.15);break;case'knockout':playSample('knockout',.2);break;case'victory':for(const [i,f] of [392,523,659,784].entries())tone(f,.18,'square',.035,i*.1);break;case'death':tone(330,.24,'square',.04);tone(247,.28,'square',.04,.2);tone(165,.55,'sawtooth',.045,.44,-95);break}}
const MUSIC_BPM=164,MUSIC_STEP=60/MUSIC_BPM/4;
function musicTone(freq,start,duration,volume=.025,type='triangle',filterFreq=1600){if(!audioCtx||!musicGain)return;const o=audioCtx.createOscillator(),filter=audioCtx.createBiquadFilter(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,start);filter.type='lowpass';filter.frequency.setValueAtTime(filterFreq,start);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(volume,start+.018);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(filter).connect(g).connect(musicGain);o.start(start);o.stop(start+duration+.03)}
function musicNoise(start,duration,volume,kind='hat'){if(!audioCtx||!musicGain)return;const length=Math.max(1,Math.ceil(audioCtx.sampleRate*duration)),buffer=audioCtx.createBuffer(1,length,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const source=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),g=audioCtx.createGain();source.buffer=buffer;filter.type=kind==='kick'?'lowpass':'highpass';filter.frequency.value=kind==='snare'?900:kind==='kick'?180:5200;g.gain.setValueAtTime(volume,start);g.gain.exponentialRampToValueAtTime(.0001,start+duration);source.connect(filter).connect(g).connect(musicGain);source.start(start)}
function scheduleMusicStep(step,start){const bar=Math.floor(step/16)%32,s=step%16,section=bar<4?'intro':bar<8?'rise':bar<16?'drop1':bar<20?'break':bar<28?'drop2':'return',stackTop=board?board.findIndex(r=>r.some(Boolean)):-1,danger=stackTop>=0&&stackTop<6,boss=enemy&&enemy.boss,boost=boss||danger?1.25:1;
 const progression=[0,-4,3,-2],rootSemi=progression[bar%4],root=73.42*Math.pow(2,rootSemi/12),drums=section!=='intro'&&section!=='break',full=section==='drop1'||section==='drop2'||boss||danger;
 if(s===0){const chord=bar%4===0?[0,3,7,10]:bar%4===1?[0,4,7,11]:bar%4===2?[0,3,7,10]:[0,5,7,10];chord.forEach((semi,i)=>musicTone(root*2*Math.pow(2,semi/12),start+i*.015,MUSIC_STEP*15,(section==='break'?.012:.008)*boost,'triangle',boss?850:1450));if(bar%8===0)musicNoise(start,MUSIC_STEP*12,.006,'hat')}
 if(drums){const kickPattern=bar%4===3?[0,3,7,9,11,14]:bar%2?[0,3,7,10,14]:[0,6,9,11,15],snarePattern=[4,12],ghostPattern=bar%2?[2,10,15]:[7,14];if(kickPattern.includes(s)){musicTone(76,start,.1,.048*boost,'sine',220);musicNoise(start,.06,.019*boost,'kick')}if(snarePattern.includes(s)){musicNoise(start,.13,.044*boost,'snare');musicTone(182,start,.04,.016,'square',600)}else if(ghostPattern.includes(s))musicNoise(start,.05,.011*boost,'snare');if(s%2===0)musicNoise(start,.024,(s%4===2?.015:.009)*boost,'hat');if(full&&s%4===3)musicNoise(start,.016,.009*boost,'hat')}
 if(section==='intro'&&s%4===2)musicNoise(start,.04,.006,'hat');if(section==='break'&&(s===4||s===12))musicNoise(start,.18,.016,'snare');
 const bassSteps=full?[0,3,6,9,11,14]:section==='rise'?[0,7,11]:section==='break'?[0,10]:[0];if(bassSteps.includes(s)){const octave=(full&&s===14)?2:1;musicTone(root/octave,start,MUSIC_STEP*(full?2.2:4.5),.034*boost,'sine',240);if(full)musicTone(root*2,start,MUSIC_STEP*.8,.007,'triangle',380)}
 const motifA=[12,null,null,7,null,10,null,null,3,null,5,null,null,2,null,null],motifB=[12,null,10,null,7,null,null,5,null,3,null,null,-2,null,2,null],motifC=[15,null,12,null,10,null,7,null,null,5,null,10,null,3,null,null],phrase=section==='drop2'?motifC:(bar%2?motifB:motifA),semi=phrase[s],melodyOn=section==='rise'||section==='drop1'||section==='drop2'||(section==='return'&&bar<31);if(melodyOn&&semi!==null&&(bar%4!==3||s<8)){const freq=293.66*Math.pow(2,semi/12);musicTone(freq,start,MUSIC_STEP*(section==='drop2'?2.6:3.4),.013*boost,boss?'square':'sine',boss?1250:2300);musicTone(freq/2,start+.028,MUSIC_STEP*3,.0045,'triangle',1050)}
 if((bar===19||bar===31)&&s>=12)musicNoise(start,MUSIC_STEP*2,.012,'hat')}
function musicScheduler(){if(!audioCtx||!musicGain)return;while(musicNextTime<audioCtx.currentTime+.16){scheduleMusicStep(musicStep,musicNextTime);musicNextTime+=MUSIC_STEP;musicStep=(musicStep+1)%512}const target=!musicEnabled?0:((paused||gameOver) ? 0.65 : 4);musicGain.gain.setTargetAtTime(target,audioCtx.currentTime,.06)}
function startMusic(){const ac=ensureAudio();if(!ac||musicTimer)return;musicGain=ac.createGain();musicGain.gain.value=0;musicCompressor=ac.createDynamicsCompressor();musicCompressor.threshold.value=-12;musicCompressor.knee.value=8;musicCompressor.ratio.value=8;musicCompressor.attack.value=.004;musicCompressor.release.value=.14;musicGain.connect(musicCompressor).connect(ac.destination);musicStep=0;musicNextTime=ac.currentTime+.08;musicTimer=setInterval(musicScheduler,45)}
const COLS=10,ROWS=20,CELL=36;
const BOARD_FX_SPEED=.84;
const COLORS=['#46425e','#00b9be','#ffeecc','#ff6973','#ffb0a3','#15788c','#00b9be','#ff6973','#ffb0a3','#15788c','#ff6973'];
const SHAPES={I:[[1,1,1,1]],O:[[2,2],[2,2]],T:[[0,3,0],[3,3,3]],L:[[0,0,4],[4,4,4]],J:[[5,0,0],[5,5,5]],S:[[0,6,6],[6,6,0]],Z:[[7,7,0],[0,7,7]]};
const BOMB_SHAPE=[[8,8],[8,8]];
const TENTACLE_SHAPES=[
 [[11,11,0,0],[0,11,11,0],[0,0,11,11]],
 [[11,0,0],[11,11,0],[0,11,11],[0,0,11]],
 [[11,11,11,0],[0,0,11,0],[0,0,11,11]]
];
const KEYS=Object.keys(SHAPES);
let board,piece,bag,nextPieceType=null,nextPieceType2=null,hold=null,hold2=null,canHold=true,dropTimer=0,last=0,paused=false,gameOver=false;
let piecesUntilBomb=0,forcedSealedPieces=0,forcedBombPieces=0,emergencyBombTriggered=false;
let particles=[],floaters=[],trails=[],shakePower=0,shakeUntil=0,hitStopUntil=0;
let clearZoomUntil=0,clearZoomStart=0,clearZoomDuration=0,clearZoomPower=0,clearZoomCx=0,clearZoomCy=0,clearZoomCells=[],clearZoomFlashUntil=0;
let pieceFx={nudgeX:0,nudgeY:0,squash:0,flash:0,spin:0,hardDrop:false,spawn:0};
let comboCount=0,comboTimer=0,overdriveMeter=0,overdriveUntil=0,shimmerClock=0;
let emergencySlowUntil=0;
let enemyHpLagValue=0,playerHpLagValue=100,enemyLagHoldUntil=0,playerLagHoldUntil=0;
let transitionTimers=[],pendingLevelUps=0;
let gameScore,totalLines,playerHp,currentFloor,enemy,lockedPieces,spawnedPieces,attackDamage,playerArmor,currentXp,playerLevel,xpNeed,buffs,meta,runShards,attackPrice,armorPrice;
let runStats;
const enemies=[
 {kind:'goblin',name:'Chrome Strider',attackName:'ORBITAL STRIKE',hp:72,attack:9,clock:4,portrait:'assets/enemy_chrome_strider_v3.png',effect:'Chrome limbs converge: direct HP damage'},
 {kind:'slime',name:'Memory Pool',attackName:'MEMORY RISE',hp:88,attack:0,corrosion:2,clock:3,portrait:'assets/enemy_memory_pool_v3.png',effect:'Adds liquid memory; clearing lines deals 2 feedback damage each'},
 {kind:'jester',name:'Chaos Jester',attackName:'GRAND SHUFFLE',hp:104,attack:6,clock:5,portrait:'assets/enemy_chaos_jester_v3.png',effect:'Scrambles the stack and deals chaos HP damage'}
];
const bossEnemy={kind:'boss',name:'The Monument',attackName:'FALLING WALL',hp:180,attack:12,clock:5,portrait:'assets/enemy_monument_v3.png',effect:'Raises two garbage rows',boss:true};
const upgrades=[
 {name:'Edge Driver',icon:'blessing-edge',desc:'+4 line damage.',apply:()=>attackDamage+=4},
 {name:'Shell Layer',icon:'blessing-shell',desc:'+3 armor against enemy attacks.',apply:()=>playerArmor+=3},
 {name:'Vital Recall',icon:'blessing-recall',desc:'Restore 30 HP.',apply:()=>playerHp=Math.min(100,playerHp+30)},
 {name:'Cascade Logic',icon:'blessing-cascade',desc:'Multi-line clears deal extra damage.',apply:()=>buffs.combo=(buffs.combo||0)+1},
 {name:'Kill Switch',icon:'blessing-kill',desc:'+35% damage to wounded enemies.',apply:()=>buffs.execute=(buffs.execute||0)+.35},
 {name:'Clock Drag',icon:'blessing-clock',desc:'Pieces fall 12% slower.',apply:()=>buffs.slow=(buffs.slow||0)+.12},
 {name:'Signal Well',icon:'blessing-well',desc:'Gain 25% more XP.',apply:()=>buffs.xp=(buffs.xp||0)+.25},
 {name:'Hard Lock',icon:'blessing-lock',desc:'Periodic bonus armor.',apply:()=>buffs.fortify=(buffs.fortify||0)+2},
 {name:'Leech Circuit',icon:'blessing-leech',desc:'Heal 3 HP for every cleared line.',apply:()=>buffs.vampire=(buffs.vampire||0)+1},
 {name:'Probability Spike',icon:'blessing-chance',desc:'15% chance for double line damage.',apply:()=>buffs.critical=(buffs.critical||0)+.15},
 {name:'Spectrum Loop',icon:'blessing-spectrum',desc:'Every 5th piece grants bonus Fury.',apply:()=>buffs.wild=(buffs.wild||0)+1}
];
function emptyBoard(){return Array.from({length:ROWS},()=>Array(COLS).fill(0))}
function refillBag(){bag=[...KEYS];for(let i=bag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]]}}
function nextType(){if(!bag.length)refillBag();return bag.pop()}
function isSealedType(type){return typeof type==='string'&&type.startsWith('SEALED:')}
function isTentacleType(type){return typeof type==='string'&&type.startsWith('TENTACLE:')}
function queuedType(){if(forcedBombPieces>0){forcedBombPieces--;return'BOMB'}if(piecesUntilBomb<=0){piecesUntilBomb=7+Math.floor(Math.random()*2);return'BOMB'}piecesUntilBomb--;const type=nextType();if(type!=='O'&&forcedSealedPieces>0){forcedSealedPieces--;return`SEALED:${type}`}return type!=='O'&&Math.random()<1/9?`SEALED:${type}`:type}
function shapeFor(type){if(type==='BOMB')return BOMB_SHAPE;if(isTentacleType(type))return TENTACLE_SHAPES[Number(type.slice(9))]||TENTACLE_SHAPES[0];if(isSealedType(type))return SHAPES[type.slice(7)].map(row=>row.map(v=>v?10:0));return SHAPES[type]}
function clone(m){return m.map(r=>[...r])}
function spawn(type=null){if(type===null){if(nextPieceType===null){spawnedPieces=0;piecesUntilBomb=7+Math.floor(Math.random()*2);nextPieceType=queuedType();nextPieceType2=queuedType()}type=nextPieceType;nextPieceType=nextPieceType2;nextPieceType2=queuedType();spawnedPieces++}const shape=shapeFor(type),sealed=isSealedType(type);piece={type,m:clone(shape),x:Math.floor((COLS-shape[0].length)/2),y:-1,sealed,wild:!sealed&&type!=='BOMB'&&!!buffs.wild&&spawnedPieces%5===0};pieceFx={nudgeX:0,nudgeY:-5,squash:.45,flash:1,spin:0,hardDrop:false,spawn:1};canHold=true;if(collides(piece.x,piece.y,piece.m))endRun()}
function collides(px,py,m){for(let y=0;y<m.length;y++)for(let x=0;x<m[y].length;x++)if(m[y][x]){const bx=px+x,by=py+y;if(bx<0||bx>=COLS||by>=ROWS||(by>=0&&board[by][bx]))return true}return false}
function landingBurst(power=1){const bottom=piece.y+piece.m.length;piece.m.forEach((r,y)=>r.forEach((v,x)=>{if(v&&y===piece.m.length-1){for(let i=0;i<3+power;i++)particles.push({x:(piece.x+x)*CELL+CELL/2,y:Math.min(ROWS*CELL-3,bottom*CELL-3),vx:(Math.random()-.5)*(2.5+power),vy:-Math.random()*(1.4+power*.35),life:180+Math.random()*180,size:2+Math.random()*3,color:v===11?'#ff6973':COLORS[v]})}}))}
function nearMissSparks(){
 const cells=[];piece.m.forEach((r,y)=>r.forEach((v,x)=>{if(v){const bx=piece.x+x,by=piece.y+y;if(by>=0){const left=bx===0||board[by][bx-1];const right=bx===COLS-1||board[by][bx+1];if(left&&right)cells.push({x:bx,y:by,v})}}}));
 cells.forEach(c=>{for(let i=0;i<7;i++)particles.push({x:c.x*CELL+CELL/2,y:c.y*CELL+CELL/2,vx:(Math.random()-.5)*5,vy:(Math.random()-.5)*3,life:180+Math.random()*160,size:2+Math.random()*2,color:'#ffe07a'})});
 if(cells.length)floaters.push({text:'TIGHT!',x:cells[0].x*CELL+CELL/2,y:cells[0].y*CELL,life:450,max:450,size:14});
}
function detonateBomb(){sfx('bomb');runStats.bombs++;for(let y=ROWS-3;y<ROWS;y++)for(let x=0;x<COLS;x++)for(let i=0;i<3;i++)particles.push({x:x*CELL+CELL/2,y:y*CELL+CELL/2,vx:(Math.random()-.5)*8,vy:-2-Math.random()*6,life:520+Math.random()*380,size:3+Math.random()*5,color:i%2?'#fff':'#777'});board.splice(ROWS-3,3);while(board.length<ROWS)board.unshift(Array(COLS).fill(0));totalLines+=3;gameScore+=300;let dealt=Math.round(attackDamage*2*(performance.now()<overdriveUntil?1.5:1));if(enemy.hp<enemy.maxHp/2)dealt=Math.round(dealt*(1+(buffs.execute||0)));enemy.hp-=dealt;runStats.damage+=dealt;juiceImpact(dealt,3,[ROWS-3,ROWS-2,ROWS-1]);addOverdrive(20);floaters.push({text:'BOMB! 2× DAMAGE',x:canvas.width/2,y:canvas.height-135,life:1500,max:1500,size:32});floaters.push({text:'BOTTOM 3 CLEARED',x:canvas.width/2,y:canvas.height-90,life:1500,max:1500,size:20});shakePower=14;shakeUntil=performance.now()+610;hitStopUntil=Math.max(hitStopUntil,performance.now()+690);triggerClass(document.getElementById('gamewrap'),'bomb-detonation');if(enemy.hp<=0){winFight();return true}return false}
function merge(hard=false,dropDistance=0){pieceFx.squash=1;if(piece.type==='BOMB'){landingBurst(4);const defeated=detonateBomb();lockedPieces++;if(!defeated)enemyTurnCheck();spawn();return}sfx(hard?'hardDrop':'lock');nearMissSparks();landingBurst(hard?3:1);if(hard&&dropDistance>3){shakePower=Math.max(shakePower,Math.min(7,2+dropDistance*.18));shakeUntil=Math.max(shakeUntil,performance.now()+75)}piece.m.forEach((r,y)=>r.forEach((v,x)=>{if(v&&piece.y+y>=0)board[piece.y+y][piece.x+x]=v}));if(piece.wild)addOverdrive(Math.min(30,12+(buffs.wild-1)*4));lockedPieces++;const defeated=clearLines();if(!defeated)enemyTurnCheck();spawn()}
function burstLine(row,count){const boosted=performance.now()<overdriveUntil,total=(boosted?10:5)+count*3+Math.min(9,comboCount);for(let x=0;x<COLS;x++)for(let i=0;i<total;i++)particles.push({x:x*CELL+CELL/2,y:row*CELL+CELL/2,vx:(Math.random()-.5)*(4+count*1.4),vy:-Math.random()*(3+count*1.4)-1,life:420+Math.random()*260+count*40,size:2+Math.random()*(4+count*.6),color:COLORS[1+Math.floor(Math.random()*7)]})}
function juiceImpact(damage,lines,rows){rows.forEach(r=>burstLine(r,lines));shakePower=Math.min(12,2+lines*2.5);shakeUntil=performance.now()+165+lines*65;hitStopUntil=Math.max(hitStopUntil,performance.now()+165+lines*95);floaters.push({text:`-${damage}`,x:canvas.width-58,y:110,life:1200,max:1200,size:20+lines*3});enemyHpLagValue=Math.max(enemyHpLagValue,enemy.hp+damage);enemyLagHoldUntil=performance.now()+420;const portrait=document.querySelector('.enemy-portrait');triggerClass(portrait,'enemy-hit');transitionAfter(580,()=>portrait.classList.remove('enemy-hit'));triggerClass(document.getElementById('enemyHp'),'hp-impact');triggerClass(document.getElementById('gamewrap'),'line-clear-focus');showDamagePopup('enemyDamagePopup',`-${damage}`)}
function addOverdrive(amount){
  if(performance.now()<overdriveUntil)return;
  amount=Math.round(amount*.8);
  overdriveMeter=Math.min(100,overdriveMeter+amount);
  if(overdriveMeter>=100){
    overdriveMeter=100;overdriveUntil=performance.now()+15000;
    document.body.classList.add('overdrive');
    const splash=document.getElementById('overdriveSplash');splash.classList.remove('show');void splash.offsetWidth;splash.classList.add('show');transitionAfter(2300,()=>splash.classList.remove('show'));
    shakePower=10;shakeUntil=performance.now()+220;
  }
}
function resetCombo(){comboCount=0;comboTimer=0}
function vampireWisps(rows,healed){const sourceY=(rows[0]??ROWS-2)*CELL+CELL/2;for(let i=0;i<Math.min(36,12+healed);i++)particles.push({x:Math.random()*canvas.width,y:sourceY+Math.random()*16,vx:-1.2-Math.random()*2.5,vy:-1-Math.random()*2.5,life:520+Math.random()*320,size:2+Math.random()*4,color:i%2?'#fff':'#aaa'})}
function spawnShatterChunks(rows,n){rows.forEach(row=>{for(let i=0;i<5+n;i++){const size=7+Math.random()*6;particles.push({x:Math.random()*canvas.width,y:row*CELL+CELL/2,vx:(Math.random()-.5)*7,vy:-2-Math.random()*5,life:640+Math.random()*420,size,color:COLORS[1+Math.floor(Math.random()*7)],chunk:true,rot:Math.random()*Math.PI*2,rotSpeed:(Math.random()-.5)*.35})}})}
function triggerClearZoom(cells,n){const now=performance.now();let sx=0,sy=0;cells.forEach(c=>{sx+=c.x*CELL+CELL/2;sy+=c.y*CELL+CELL/2});clearZoomCx=sx/cells.length;clearZoomCy=sy/cells.length;clearZoomCells=cells;clearZoomPower=.2+.1*n;clearZoomStart=now;clearZoomFlashUntil=now+110;clearZoomDuration=520+n*70;clearZoomUntil=now+clearZoomDuration;hitStopUntil=Math.max(hitStopUntil,clearZoomUntil)}
function clearZoomScale(now){if(now>=clearZoomUntil)return 1;const t=(now-clearZoomStart)/clearZoomDuration;let k;if(t<.18){const x=t/.18;k=1-(1-x)*(1-x)}else if(t<.7)k=1;else{const y=(t-.7)/.3;k=1-y*y}return 1+clearZoomPower*k}
function clearLines(){const zoomCells=[];if(piece)for(let dy=0;dy<piece.m.length;dy++){const by=piece.y+dy;if(by<0||by>=ROWS||!board[by].every(Boolean))continue;piece.m[dy].forEach((v,dx)=>{if(v)zoomCells.push({x:piece.x+dx,y:by})})}let n=0,rows=[],impossibleLines=0;for(let y=ROWS-1;y>=0;y--){if(board[y].every(Boolean)){if(board[y].includes(11))impossibleLines++;rows.push(y);board.splice(y,1);board.unshift(Array(COLS).fill(0));n++;y++}}
 if(n){
  comboCount++;comboTimer=6500;
  totalLines+=n;
  const comboBonus=1+Math.max(0,comboCount-1)*.15;
  const mult=[0,1,2.3,4,7][n];
  const upgradeBonus=1+(buffs.combo||0)*Math.max(0,n-1)*.25;
  let dealt=Math.round(attackDamage*mult*upgradeBonus*comboBonus*(performance.now()<overdriveUntil?1.5:1));
  sfx(impossibleLines?'impossible':n>=3?'line3':n===2?'line2':'line1');if(impossibleLines){const impossibleBonus=attackDamage*2*impossibleLines;dealt+=impossibleBonus;gameScore+=500*impossibleLines;addOverdrive(30*impossibleLines);floaters.push({text:'IMPOSSIBLE PLACEMENT!',x:canvas.width/2,y:105,life:2200,max:2200,size:29});floaters.push({text:`+${impossibleBonus} SURREAL DAMAGE`,x:canvas.width/2,y:145,life:1800,max:1800,size:18});for(let i=0;i<42;i++)particles.push({x:Math.random()*canvas.width,y:(rows[0]??10)*CELL,vx:(Math.random()-.5)*5,vy:-1-Math.random()*4,life:650+Math.random()*650,size:5+Math.random()*7,color:['#ffeecc','#00b9be','#ff6973'][i%3],surreal:['eye','door','cloud'][i%3]})}
  if(enemy.hp<enemy.maxHp/2)dealt=Math.round(dealt*(1+(buffs.execute||0)));
  const critical=buffs.critical&&Math.random()<buffs.critical;if(critical){dealt*=2;shakePower=Math.max(shakePower,10);shakeUntil=performance.now()+180;hitStopUntil=performance.now()+90;triggerClass(document.getElementById('gamewrap'),'critical-flash')}
  enemy.hp-=dealt;runStats.damage+=dealt;runStats.bestCombo=Math.max(runStats.bestCombo,comboCount);gameScore+=Math.round(100*n*n*upgradeBonus*comboBonus*(performance.now()<overdriveUntil?2:1));
  if(enemy.boss&&enemy.phase===1&&enemy.hp>0&&enemy.hp<=enemy.maxHp/2){sfx('phase');enemy.phase=2;enemy.clock=Math.max(2,enemy.clock-1);enemy.progress=0;floaters.push({text:'PHASE 2!',x:canvas.width/2,y:255,life:1600,max:1600,size:34});shakePower=13;shakeUntil=performance.now()+650;hitStopUntil=Math.max(hitStopUntil,performance.now()+500);triggerClass(document.querySelector('.enemy-box'),'boss-phase-two')}
  if(enemy.kind==='slime'){const corrosion=n*Math.max(1,enemy.corrosion-Math.floor(playerArmor/2));floaters.push({text:`CORROSION -${corrosion} HP`,x:canvas.width/2,y:235,life:1200,max:1200,size:18});playerDamage(corrosion);if(gameOver)return true}
  if(buffs.vampire){const healed=3*n*buffs.vampire;playerHp=Math.min(100,playerHp+healed);playerHpLagValue=playerHp;floaters.push({text:`+${healed} HP`,x:55,y:105,life:700,max:700,size:16});vampireWisps(rows,healed)}
  juiceImpact(dealt,n,rows);gainXp((8*n+n*n*2)*(performance.now()<overdriveUntil?2:1));
  if(zoomCells.length)triggerClearZoom(zoomCells,n);if(n>=3)spawnShatterChunks(rows,n);
  addOverdrive(8+n*8+Math.min(18,comboCount*2));
  const clearText=n===1?'KEEP GOING':n===2?'NICE!':'MASSIVE!';floaters.push({text:clearText,x:canvas.width/2,y:145,life:1650,max:1650,size:n===1?22:n===2?29:36});if(critical)floaters.push({text:'CRITICAL!',x:canvas.width/2,y:190,life:1300,max:1300,size:23});else if(comboCount>1)floaters.push({text:`COMBO ×${comboCount}`,x:canvas.width/2,y:190,life:1250,max:1250,size:18+Math.min(12,comboCount*2)});
  const comboEl=document.getElementById('combo');comboEl.classList.remove('hot');void comboEl.offsetWidth;comboEl.classList.add('hot');
  if(enemy.hp<=0){winFight();return true}
 }else resetCombo()
 return false
}
function triggerClass(el,name){if(!el)return;el.classList.remove(name);void el.offsetWidth;el.classList.add(name)}
function showDamagePopup(id,text){const el=document.getElementById(id);if(!el)return;el.textContent=text;triggerClass(el,'show')}
function playerDamage(amount){
 sfx('hurt');
 const dealt=Math.max(1,amount),before=playerHp;runStats.damageTaken+=Math.min(before,dealt);playerHp=Math.max(0,playerHp-dealt);playerHpLagValue=Math.max(playerHpLagValue,before);playerLagHoldUntil=performance.now()+260;
 triggerClass(document.getElementById('hpStat'),'player-hit');triggerClass(document.getElementById('playerHp'),'hp-impact');showDamagePopup('playerDamagePopup',`-${dealt} HP`);
 shakePower=Math.max(shakePower,7);shakeUntil=performance.now()+170;hitStopUntil=performance.now()+65;
 if(playerHp<=0)endRun();
}
function addGarbageRow(){
 const overflow=board[0].some(Boolean);board.shift();const hole=Math.floor(Math.random()*COLS);board.push(Array.from({length:COLS},(_,x)=>x===hole?0:9));
 for(let x=0;x<COLS;x++)if(x!==hole)for(let i=0;i<4;i++)particles.push({x:x*CELL+CELL/2,y:ROWS*CELL-10,vx:(Math.random()-.5)*2.5,vy:-1-Math.random()*3,life:350+Math.random()*220,size:2+Math.random()*3,color:'#9b8b77'});
 floaters.push({text:'GARBAGE RISE!',x:canvas.width/2,y:canvas.height-70,life:1000,max:1000,size:22});triggerClass(canvas,'board-warning');
 if(overflow)endRun();
}
function scrambleBoard(){
 const blocks=board.flat().filter(Boolean);for(let i=blocks.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[blocks[i],blocks[j]]=[blocks[j],blocks[i]]}
 board=emptyBoard();let index=0;
 for(let y=ROWS-1;y>=0&&index<blocks.length;y--){const holes=new Set();while(holes.size<2)holes.add(Math.floor(Math.random()*COLS));const cells=Array.from({length:COLS},(_,x)=>x).filter(x=>!holes.has(x));for(let i=cells.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cells[i],cells[j]]=[cells[j],cells[i]]}for(const x of cells){if(index>=blocks.length)break;board[y][x]=blocks[index++]}}
 for(let i=0;i<55;i++)particles.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height,vx:(Math.random()-.5)*5,vy:(Math.random()-.5)*5,life:300+Math.random()*350,size:2+Math.random()*4,color:i%2?'#d53f95':'#8a56d6'});
 floaters.push({text:'CHAOS SHUFFLE!',x:canvas.width/2,y:canvas.height*.46,life:1200,max:1200,size:24});triggerClass(canvas,'board-warning');shakePower=11;shakeUntil=performance.now()+260;hitStopUntil=performance.now()+90;
}
function showEnemyAttackFx(kind){const fx=document.getElementById('attackFx');fx.className='';void fx.offsetWidth;fx.className=`show attack-${kind}`;transitionAfter(kind==='boss'?1250:1000,()=>{fx.className=''})}
function performEnemyAttack(){
 sfx('enemy');
 const portrait=document.querySelector('.enemy-portrait'),enemyBox=document.querySelector('.enemy-box');triggerClass(portrait,'enemy-attacking');triggerClass(enemyBox,'enemy-attacking');transitionAfter(enemy.boss?1100:900,()=>{portrait.classList.remove('enemy-attacking');enemyBox.classList.remove('enemy-attacking')});triggerClass(document.getElementById('attackTelegraph'),'attack-fired');
 showEnemyAttackFx(enemy.kind);
 if(enemy.kind==='goblin'){
   let armor=playerArmor;if(buffs.fortify&&lockedPieces%5===0)armor+=buffs.fortify;playerDamage(Math.max(1,enemy.attack-armor));
 }else if(enemy.kind==='slime')addGarbageRow();
 else if(enemy.kind==='jester'){scrambleBoard();playerDamage(Math.max(1,enemy.attack-playerArmor))}
 else if(enemy.kind==='boss'){
   if(enemy.attackIndex%2===0){addGarbageRow();if(!gameOver)addGarbageRow()}
   else{playerDamage(Math.max(1,enemy.attack-playerArmor));if(!gameOver){nextPieceType=`TENTACLE:${Math.floor(Math.random()*TENTACLE_SHAPES.length)}`;floaters.push({text:'AN IMPOSSIBLE PIECE!',x:canvas.width/2,y:170,life:1800,max:1800,size:23})}}
   enemy.attackIndex++;const wall=enemy.attackIndex%2===0;enemy.attackName=wall?'FALLING WALL':'CLOSED DOOR';enemy.effect=wall?'Raises two garbage rows':'Heavy damage; throws an impossible piece';
 }
}
function enemyTurnCheck(){enemy.progress++;if(enemy.progress>=enemy.clock){enemy.progress=0;performEnemyAttack()}else if(enemy.clock-enemy.progress===1)sfx('warning')}
function gainXp(v){currentXp+=Math.round(v*(1+(buffs.xp||0)));while(currentXp>=xpNeed){currentXp-=xpNeed;playerLevel++;xpNeed=Math.round(xpNeed*1.35);pendingLevelUps++}}
function clearTransitionTimers(){transitionTimers.forEach(clearTimeout);transitionTimers=[]}
function transitionAfter(ms,fn){const id=setTimeout(fn,ms);transitionTimers.push(id);return id}
function createTransitionShards(){
 const host=document.getElementById('transitionShards');host.innerHTML='';
 const rect=document.querySelector('.enemy-portrait').getBoundingClientRect();
 for(let i=0;i<32;i++){
  const shard=document.createElement('i');shard.className='transition-shard';
  shard.style.left=(rect.left+rect.width*(.2+Math.random()*.6))+'px';shard.style.top=(rect.top+rect.height*(.2+Math.random()*.6))+'px';
  shard.style.setProperty('--dx',((Math.random()-.5)*420)+'px');shard.style.setProperty('--dy',(-80+Math.random()*340)+'px');
  shard.style.color=i%3===0?'#8d4bc2':i%3===1?'#d35443':'#e8bd59';shard.style.background='currentColor';
  shard.style.animationDelay=(Math.random()*.12)+'s';host.appendChild(shard);
 }
}
function flyShardsToWallet(){const host=document.getElementById('shardFlights'),from=document.querySelector('.enemy-portrait').getBoundingClientRect(),to=document.getElementById('shards').getBoundingClientRect();host.innerHTML='';for(let i=0;i<5;i++){const shard=document.createElement('i');shard.className='wallet-shard-flight';const sx=from.left+from.width/2+(i-2)*7,sy=from.top+from.height/2;shard.style.left=sx+'px';shard.style.top=sy+'px';shard.style.setProperty('--dx',(to.left+to.width/2-sx)+'px');shard.style.setProperty('--dy',(to.top+to.height/2-sy)+'px');shard.style.animationDelay=(i*.08)+'s';host.appendChild(shard)}transitionAfter(1050,()=>{host.innerHTML='';triggerClass(document.getElementById('shards'),'wallet-impact')})}
function showPostFightScreen(onDone){
 const bossWon=!!enemy.boss;
 const relics=[{key:'openWindow',name:'Open Window',icon:'icon-next',desc:'Reveal a second upcoming piece.'},{key:'emptyFrame',name:'Empty Frame',icon:'icon-hold',desc:'Gain a second Hold slot. Press C to cycle stored pieces.'}].filter(r=>!buffs[r.key]);
 const useRelics=bossWon&&relics.length>0;
 const randomBlessing=upgrades[Math.floor(Math.random()*upgrades.length)];
 const rewards=[
  {name:'Memory Patch',glyph:'repair',code:'RESTORE',desc:'Recover 25 HP.',apply:()=>{playerHp=Math.min(100,playerHp+25);playerHpLagValue=playerHp}},
  {name:'Pattern Graft',glyph:'pattern',code:'IMPRINT',desc:`Install ${randomBlessing.name}. ${randomBlessing.desc}`,apply:randomBlessing.apply},
  {name:'Redline Core',glyph:'redline',code:'UNSTABLE',desc:'+6 damage. Lose 15 HP.',apply:()=>{attackDamage+=6;playerHp=Math.max(1,playerHp-15);playerHpLagValue=playerHp}}
 ];
 let rewardTaken=false,relicTaken=false;
 const modal=document.getElementById('modal');
 const render=()=>{
  const canShop=runShards>=Math.min(attackPrice,armorPrice);
  const primaryDone=useRelics?relicTaken:rewardTaken;
  const canDescend=pendingLevelUps<=0&&primaryDone;
  let html='<h2>Recovered Signal</h2>';
  if(pendingLevelUps>0)html+='<div class="section-title">Level Up!</div><div class="small">Choose a blessing.</div><div class="choices blessing-choices" id="levelUpChoices"></div>';
  if(!primaryDone)html+=useRelics?'<div class="section-title">Impossible Relic</div><div class="small">Choose what remains after the boss disappears.</div><div class="reward-choices boss-relics" id="relicChoices"></div>':'<div class="section-title">Extract an Artifact</div><div class="small">Extract one artifact before descent.</div><div class="reward-choices artifact-choices" id="rewardChoices"></div>';
  if(canShop)html+=`<div class="section-title">Upgrade Terminal</div><div class="shop-wallet"><i class="fragment-glyph" aria-hidden="true"></i> ${runShards} FRAGMENTS</div><div class="choices shop-choices"><button class="choice blessing-choice" id="buyAttack"><b><i class="blessing-glyph blessing-edge" aria-hidden="true"></i>Raise Output</b><span>+2 Damage · ${attackPrice} fragments</span></button><button class="choice blessing-choice" id="buyArmor"><b><i class="blessing-glyph blessing-shell" aria-hidden="true"></i>Harden Shell</b><span>+1 Armor · ${armorPrice} fragments</span></button></div>`;
  html+=`<button class="big-button shop-continue" id="leaveShop"${canDescend?'':' disabled'}>Descend</button>`;
  modal.innerHTML=html;
  if(pendingLevelUps>0){
   const host=modal.querySelector('#levelUpChoices'),pool=[...upgrades].sort(()=>Math.random()-.5).slice(0,3);
   pool.forEach(u=>{const b=document.createElement('button');b.className='choice blessing-choice';b.innerHTML=`<b><i class="blessing-glyph ${u.icon}" aria-hidden="true"></i>${u.name}</b><span>${u.desc}</span>`;b.onclick=()=>{u.apply();pendingLevelUps--;render()};host.appendChild(b)});
  }
  if(!primaryDone){
   if(useRelics){
    const host=modal.querySelector('#relicChoices');
    relics.forEach(r=>{const b=document.createElement('button');b.className='choice reward-choice';b.innerHTML=`<b><i class="hud-icon ${r.icon}" aria-hidden="true"></i>${r.name}</b><span>${r.desc}</span>`;b.onclick=()=>{buffs[r.key]=1;relicTaken=true;updateUI();render()};host.appendChild(b)});
   }else{
    const host=modal.querySelector('#rewardChoices');
    rewards.forEach(r=>{const b=document.createElement('button');b.className=`choice reward-choice artifact-choice artifact-${r.glyph}`;b.innerHTML=`<b><i class="reward-artifact" aria-hidden="true"></i><span class="artifact-name"><small>${r.code}</small>${r.name}</span></b><span>${r.desc}</span>`;b.onclick=()=>{r.apply();rewardTaken=true;render()};host.appendChild(b)});
   }
  }
  if(canShop){
   const attack=modal.querySelector('#buyAttack'),armor=modal.querySelector('#buyArmor');
   attack.disabled=runShards<attackPrice;armor.disabled=runShards<armorPrice;
   attack.onclick=()=>{runShards-=attackPrice;attackDamage+=2;attackPrice+=5;runStats.shardsSpent+=attackPrice-5;runStats.attackBuys++;updateUI();render()};
   armor.onclick=()=>{runShards-=armorPrice;playerArmor+=1;armorPrice+=5;runStats.shardsSpent+=armorPrice-5;runStats.armorBuys++;updateUI();render()};
  }
  if(canDescend)modal.querySelector('#leaveShop').onclick=()=>{hideOverlay();onDone()};
 };
 render();showOverlay();
}
function beginNextFloor(){currentFloor++;enemy=makeEnemy();enemyHpLagValue=enemy.hp;enemyLagHoldUntil=0;const portrait=document.querySelector('.enemy-portrait'),box=document.querySelector('.enemy-box'),layer=document.getElementById('floorTransition');box.classList.remove('boss-phase-two');document.getElementById('transitionFloor').textContent=`FLOOR ${currentFloor}`;document.getElementById('transitionEnemy').textContent=enemy.name;document.getElementById('transitionEffect').textContent=enemy.effect;layer.classList.add('show');layer.setAttribute('aria-hidden','false');updateUI();portrait.classList.remove('enemy-dying');triggerClass(portrait,'enemy-entering');transitionAfter(1280,()=>{layer.classList.remove('show');layer.setAttribute('aria-hidden','true');portrait.classList.remove('enemy-entering');box.classList.remove('enemy-death-impact');paused=false})}
function winFight(){if(paused&&document.getElementById('floorTransition').classList.contains('show'))return;sfx('knockout');transitionAfter(560,()=>sfx('victory'));runStats.enemies++;runShards+=5;runStats.shardsEarned+=5;paused=true;hitStopUntil=performance.now()+125;shakePower=12;shakeUntil=performance.now()+300;const portrait=document.querySelector('.enemy-portrait'),box=document.querySelector('.enemy-box'),bossWon=!!enemy.boss,striderWon=enemy.kind==='goblin';triggerClass(portrait,'enemy-dying');triggerClass(box,'enemy-death-impact');createTransitionShards();flyShardsToWallet();floaters.push({text:bossWon?'BOSS UNPLACED!  +5 FRAGMENTS':'FOE DEFEATED!  +5 FRAGMENTS',x:canvas.width/2,y:canvas.height*.32,life:bossWon?1900:1100,max:bossWon?1900:1100,size:26});if(bossWon){const finale=document.getElementById('bossDefeat');finale.classList.remove('show');void finale.offsetWidth;finale.classList.add('show');transitionAfter(2100,()=>{finale.classList.remove('show');showPostFightScreen(beginNextFloor)})}else transitionAfter(striderWon?1150:620,()=>showPostFightScreen(beginNextFloor))}
function makeEnemy(){const routeStep=(currentFloor-1)%5,boss=routeStep===4,elite=routeStep===3,cycle=Math.floor((currentFloor-1)/5),base=boss?bossEnemy:elite?enemies[cycle%enemies.length]:enemies[routeStep],scale=(1+(currentFloor-1)*.17)*(elite?1.25:1),hp=Math.round(base.hp*scale);return{...base,name:elite?`Elite ${base.name}`:base.name,effect:elite?`Elite: ${base.effect}`:base.effect,maxHp:hp,hp,attack:Math.round(base.attack*(1+(currentFloor-1)*.11)*(elite?1.2:1)),clock:Math.max(2,base.clock-Math.floor((currentFloor-1)/7)-(elite?1:0)),progress:0,phase:base.boss?1:0,attackIndex:0,elite}}
function rotate(dir=1){if(piece.sealed){pieceFx.nudgeX=dir*3;pieceFx.squash=.18;shakePower=Math.max(shakePower,1.5);shakeUntil=Math.max(shakeUntil,performance.now()+45);floaters.push({text:'SEALED!',x:(piece.x+piece.m[0].length/2)*CELL,y:Math.max(25,piece.y*CELL),life:420,max:420,size:14});return}const m=piece.m;const r=dir>0?m[0].map((_,i)=>m.map(row=>row[i]).reverse()):m[0].map((_,i)=>m.map(row=>row[row.length-1-i]));for(const kick of [0,-1,1,-2,2])if(!collides(piece.x+kick,piece.y,r)){piece.x+=kick;piece.m=r;pieceFx.spin=dir*.12;pieceFx.flash=1;pieceFx.squash=.22;sfx('rotate');break}}
function move(dx){if(!collides(piece.x+dx,piece.y,piece.m)){piece.x+=dx;pieceFx.nudgeX=-dx*5;pieceFx.squash=.12;sfx('move')}else{pieceFx.nudgeX=dx*2;shakePower=Math.max(shakePower,1);shakeUntil=Math.max(shakeUntil,performance.now()+28)}}
function drop(){if(!collides(piece.x,piece.y+1,piece.m))piece.y++;else merge(false,0)}
function hardDrop(){const startY=piece.y;let distance=0;while(!collides(piece.x,piece.y+1,piece.m)){piece.y++;distance++}
 if(distance>0){piece.m.forEach((r,y)=>r.forEach((v,x)=>{if(v)trails.push({x:(piece.x+x)*CELL+CELL/2,y1:(startY+y)*CELL+CELL/2,y2:(piece.y+y)*CELL+CELL/2,life:150,max:150,color:v===11?'#ff6973':COLORS[v]})}));addOverdrive(Math.min(12,2+distance*.45));}gameScore+=2+distance;pieceFx.hardDrop=true;pieceFx.nudgeY=-Math.min(10,distance*.6);merge(true,distance)}
function doHold(){if(!canHold)return;const t=piece.type;if(buffs.emptyFrame&&hold&&hold2){const swap=hold;hold=hold2;hold2=t;spawn(swap)}else if(buffs.emptyFrame&&hold&&!hold2){hold2=t;spawn()}else if(hold){const swap=hold;hold=t;spawn(swap)}else{hold=t;spawn()}canHold=false}
function reset(){clearTransitionTimers();document.getElementById('floorTransition').classList.remove('show');document.getElementById('bossDefeat').classList.remove('show');document.getElementById('overdriveSplash').classList.remove('show');document.getElementById('attackFx').className='';document.getElementById('emergencyFx').className='';document.querySelector('.enemy-portrait').classList.remove('enemy-dying','enemy-entering');document.querySelector('.enemy-box').classList.remove('enemy-death-impact','boss-phase-two');particles=[];floaters=[];trails=[];clearZoomUntil=0;clearZoomFlashUntil=0;clearZoomCells=[];comboCount=0;comboTimer=0;overdriveMeter=0;overdriveUntil=0;emergencySlowUntil=0;pendingLevelUps=0;forcedSealedPieces=0;forcedBombPieces=0;emergencyBombTriggered=false;document.body.classList.remove('overdrive','emergency-rescue');shakePower=0;shakeUntil=0;hitStopUntil=0;pieceFx={nudgeX:0,nudgeY:0,squash:0,flash:0,spin:0,hardDrop:false,spawn:0};board=emptyBoard();bag=[];nextPieceType=null;nextPieceType2=null;hold=null;hold2=null;gameScore=0;totalLines=0;playerHp=100;currentFloor=1;lockedPieces=0;runShards=0;attackPrice=5;armorPrice=5;runStats={started:Date.now(),damage:0,damageTaken:0,bestCombo:0,bombs:0,enemies:0,shardsEarned:0,shardsSpent:0,attackBuys:0,armorBuys:0};attackDamage=10;playerArmor=0;currentXp=0;playerLevel=1;xpNeed=30;buffs={};enemy=makeEnemy();enemyHpLagValue=enemy.hp;playerHpLagValue=playerHp;enemyLagHoldUntil=0;playerLagHoldUntil=0;paused=false;gameOver=false;hideOverlay();spawn();updateUI()}
function drawSlimeCell(x,y,px,py,s){
 const phase=Math.floor(performance.now()/220+x)%4,left=x>0&&board[y][x-1]===9,right=x<COLS-1&&board[y][x+1]===9,top=py+2,bottom=py+s-2;
 // A seamless wall base lets the droplet texture continue across cell boundaries.
 ctx.fillStyle='#15788c';ctx.fillRect(px-2,top,s+4,bottom-top);if(left)ctx.fillRect(px-5,top,7,bottom-top);if(right)ctx.fillRect(px+s-2,top,7,bottom-top);
 ctx.fillStyle='#00b9be';ctx.fillRect(px,top,s,3);ctx.fillRect(px+2,bottom-4,s-4,3);
 const drop=(dx,dy,tall=false)=>{const h=tall?14:12;ctx.fillStyle='#46425e';ctx.fillRect(dx+4,dy+1,3,3);ctx.fillRect(dx+3,dy+4,6,h-5);ctx.fillRect(dx+1,dy+7,10,h-9);ctx.fillRect(dx+3,dy+h-2,6,3);ctx.fillStyle='#00b9be';ctx.fillRect(dx+4,dy,3,3);ctx.fillRect(dx+3,dy+3,6,h-5);ctx.fillRect(dx+2,dy+6,8,h-8);ctx.fillRect(dx+4,dy+h-3,4,2);ctx.fillStyle='#ffeecc';ctx.fillRect(dx+4,dy+4,2,5);ctx.fillRect(dx+6,dy+3,2,3);ctx.fillStyle='#ffb0a3';ctx.fillRect(dx+7,dy+h-5,2,2)};
 // Four larger glossy drops remain readable while the pieces are moving quickly.
 const bob=phase===1?1:0;drop(px+1,top+1+bob,true);drop(px+18,top+3,false);drop(px+8,top+16,false);drop(px+23,top+14+bob,true);
}
function drawShimmer(x,y,px,py,s){const step=Math.floor(shimmerClock/90)%9,band=((step-(x+y))%9+9)%9;if(band>2)return;const base=ctx.globalAlpha;ctx.globalAlpha=base*(band===0?.34:.16);ctx.fillStyle='#ffeecc';ctx.fillRect(px+2,py+2,s-4,s-4);ctx.globalAlpha=base}
function drawCell(x,y,v,alpha=1){const px=x*CELL+2,py=y*CELL+2,s=CELL-4;ctx.globalAlpha=alpha;if(v===9)drawSlimeCell(x,y,px,py,s);else{ctx.fillStyle=v===11?'#ff6973':COLORS[v];ctx.fillRect(px,py,s,s);ctx.fillStyle='#ffeecc';ctx.fillRect(px+3,py+3,s-6,4);ctx.fillStyle=v===11?'#00b9be':'#ffb0a3';ctx.fillRect(px+3,py+7,4,s-13);ctx.fillStyle='#46425e';ctx.fillRect(px+5,py+s-6,s-10,3);ctx.fillRect(px+s-7,py+7,3,s-13);ctx.strokeStyle='#46425e';ctx.lineWidth=2;ctx.strokeRect(px+1,py+1,s-2,s-2);if(v===10){ctx.fillStyle='#46425e';ctx.fillRect(px+9,py+12,s-18,10);ctx.fillRect(px+12,py+8,s-24,6);ctx.fillStyle='#ffeecc';ctx.fillRect(px+13,py+14,s-26,5)}else if(v===11){ctx.fillStyle='#46425e';ctx.fillRect(px+11,py+12,5,5);ctx.fillRect(px+20,py+19,4,4);ctx.fillStyle='#ffeecc';ctx.fillRect(px+12,py+13,2,2)}drawShimmer(x,y,px,py,s)}ctx.globalAlpha=1}
function updateEffects(dt){const fxdt=dt*BOARD_FX_SPEED;shimmerClock+=fxdt;const ease=Math.min(1,fxdt/70),now=performance.now();if(now>enemyLagHoldUntil)enemyHpLagValue+=(Math.max(0,enemy.hp)-enemyHpLagValue)*Math.min(1,dt/180);if(now>playerLagHoldUntil)playerHpLagValue+=(playerHp-playerHpLagValue)*Math.min(1,dt/180);comboTimer=Math.max(0,comboTimer-dt);if(comboTimer===0&&comboCount)resetCombo();if(overdriveUntil&&now>=overdriveUntil){overdriveUntil=0;overdriveMeter=0;document.body.classList.remove('overdrive')}pieceFx.nudgeX*=1-ease;pieceFx.nudgeY*=1-ease;pieceFx.spin*=1-ease;pieceFx.squash*=Math.max(0,1-fxdt/95);pieceFx.flash*=Math.max(0,1-fxdt/115);pieceFx.spawn*=Math.max(0,1-fxdt/120);particles.forEach(p=>{p.x+=p.vx*BOARD_FX_SPEED;p.y+=p.vy*BOARD_FX_SPEED;p.vy+=.12*BOARD_FX_SPEED;p.life-=fxdt;if(p.chunk)p.rot=(p.rot||0)+(p.rotSpeed||0)*BOARD_FX_SPEED});particles=particles.filter(p=>p.life>0);trails.forEach(t=>t.life-=fxdt);trails=trails.filter(t=>t.life>0);floaters.forEach(f=>{f.y-=fxdt*.045;f.life-=fxdt});floaters=floaters.filter(f=>f.life>0)}
function drawEffects(){trails.forEach(t=>{ctx.globalAlpha=Math.max(0,t.life/t.max)*.55;ctx.strokeStyle=t.color;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(t.x,t.y1);ctx.lineTo(t.x,t.y2);ctx.stroke()});ctx.globalAlpha=1;particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/680);ctx.fillStyle=p.color;if(p.surreal==='eye'){ctx.fillRect(Math.round(p.x-p.size),Math.round(p.y),Math.ceil(p.size*2),Math.ceil(p.size*.72));ctx.fillStyle='#46425e';ctx.fillRect(Math.round(p.x-2),Math.round(p.y),4,Math.ceil(p.size*.72))}else if(p.surreal==='door'){ctx.fillRect(Math.round(p.x-p.size*.45),Math.round(p.y-p.size),Math.ceil(p.size*.9),Math.ceil(p.size*1.6));ctx.fillStyle='#46425e';ctx.fillRect(Math.round(p.x+p.size*.18),Math.round(p.y),2,2)}else if(p.surreal==='cloud'){ctx.fillRect(Math.round(p.x-p.size),Math.round(p.y),Math.ceil(p.size*2),Math.ceil(p.size*.65));ctx.fillRect(Math.round(p.x-p.size*.55),Math.round(p.y-p.size*.45),Math.ceil(p.size*.75),Math.ceil(p.size*.7));ctx.fillRect(Math.round(p.x+p.size*.08),Math.round(p.y-p.size*.65),Math.ceil(p.size*.8),Math.ceil(p.size*.9))}else if(p.chunk){ctx.save();ctx.translate(Math.round(p.x),Math.round(p.y));ctx.rotate(p.rot||0);const cs=p.size;ctx.fillRect(-cs/2,-cs/2,cs,cs);ctx.fillStyle='#ffeecc';ctx.fillRect(-cs/2+1,-cs/2+1,cs-2,Math.max(1,cs*.3));ctx.fillStyle='#46425e';ctx.fillRect(-cs/2+1,cs/2-Math.max(1,cs*.3)-1,cs-2,Math.max(1,cs*.3));ctx.restore()}else ctx.fillRect(Math.round(p.x),Math.round(p.y),Math.ceil(p.size),Math.ceil(p.size))});ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='24px "Ari W9500"';floaters.forEach(f=>{ctx.globalAlpha=Math.max(0,f.life/f.max);ctx.fillStyle='#ffe07a';ctx.strokeStyle='#4b1515';ctx.lineWidth=5;ctx.strokeText(f.text,f.x,f.y);ctx.fillText(f.text,f.x,f.y)});ctx.globalAlpha=1;ctx.textAlign='start'}
function drawOverdrivePieceFlames(){const phase=Math.floor(performance.now()/85)%4;for(let x=0;x<piece.m[0].length;x++){let top=-1;for(let y=0;y<piece.m.length;y++)if(piece.m[y][x]){top=y;break}if(top<0||piece.y+top<0)continue;const px=(piece.x+x)*CELL,py=(piece.y+top)*CELL,wave=(x+phase)%3;ctx.fillStyle='#ff6973';ctx.fillRect(px+4,py-8-wave*3,CELL-8,10+wave*3);ctx.fillStyle='#ffb0a3';ctx.fillRect(px+9,py-14+wave*2,CELL-18,12);ctx.fillStyle='#ffeecc';ctx.fillRect(px+14+(phase%2)*3,py-11-wave*2,7,9);ctx.fillStyle='#46425e';ctx.fillRect(px+4,py-8-wave*3,5,5);ctx.fillRect(px+CELL-9,py-5-wave*2,5,5)}}
function drawActivePiece(){const w=piece.m[0].length*CELL,h=piece.m.length*CELL,cx=(piece.x*CELL)+w/2,cy=(piece.y*CELL)+h/2;ctx.save();ctx.translate(cx+pieceFx.nudgeX,cy+pieceFx.nudgeY);ctx.rotate(pieceFx.spin);const breathe=Math.round(Math.sin(performance.now()/230))*.01,sx=1+breathe+pieceFx.squash*.18,sy=1-breathe-pieceFx.squash*.20;const pop=1+pieceFx.spawn*.22;ctx.scale(sx*pop,sy*pop);ctx.translate(-cx,-cy);ctx.shadowColor='transparent';ctx.shadowBlur=0;if(performance.now()<overdriveUntil)drawOverdrivePieceFlames();piece.m.forEach((r,y)=>r.forEach((v,x)=>{if(v&&piece.y+y>=0)drawCell(piece.x+x,piece.y+y,v)}));if(piece.type==='BOMB'){const pulse=Math.floor(performance.now()/140)%2;ctx.fillStyle=pulse?'#111':'#555';ctx.fillRect(piece.x*CELL+CELL-10,piece.y*CELL+CELL-10,20,20);ctx.fillStyle='#fff';ctx.fillRect(piece.x*CELL+CELL-4,piece.y*CELL+CELL-4,8,8);ctx.fillStyle='#111';ctx.fillRect(piece.x*CELL+CELL+8,piece.y*CELL-2,5,14)}if(piece.wild){const phase=Math.floor(performance.now()/110)%2;ctx.globalAlpha=phase?.48:.2;ctx.fillStyle=phase?'#fff':'#777';piece.m.forEach((r,y)=>r.forEach((v,x)=>{if(v&&piece.y+y>=0){for(let py=0;py<3;py++)for(let px=0;px<3;px++)if((px+py+phase)%2===0)ctx.fillRect((piece.x+x)*CELL+5+px*9,(piece.y+y)*CELL+5+py*9,5,5)}}));ctx.globalAlpha=1}if(pieceFx.flash>0){ctx.globalAlpha=pieceFx.flash>.5?1:.35;ctx.fillStyle='#fff1cf';piece.m.forEach((r,y)=>r.forEach((v,x)=>{if(v&&piece.y+y>=0)ctx.fillRect((piece.x+x)*CELL+7,(piece.y+y)*CELL+7,CELL-14,CELL-14)}));ctx.globalAlpha=1}ctx.restore()}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();const now=performance.now();if(now<shakeUntil){ctx.translate((Math.random()-.5)*shakePower*2,(Math.random()-.5)*shakePower*2)}if(now<clearZoomUntil){const zs=clearZoomScale(now);ctx.translate(clearZoomCx,clearZoomCy);ctx.scale(zs,zs);ctx.translate(-clearZoomCx,-clearZoomCy)}ctx.fillStyle='#46425e';ctx.fillRect(-16,-16,canvas.width+32,canvas.height+32);ctx.strokeStyle='rgba(0,185,190,.18)';ctx.lineWidth=1;for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x*CELL+.5,0);ctx.lineTo(x*CELL+.5,ROWS*CELL);ctx.stroke()}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y*CELL+.5);ctx.lineTo(COLS*CELL,y*CELL+.5);ctx.stroke()}for(let i=0;i<12;i++){const mx=(i*97+31)%canvas.width,my=(now*.018+i*83)%canvas.height;ctx.globalAlpha=.18+.14*Math.sin(now/430+i);ctx.fillStyle=i%3?'#00b9be':'#ff6973';ctx.fillRect(mx,Math.floor(my),i%4===0?3:2,i%4===0?3:2)}ctx.globalAlpha=1;board.forEach((r,y)=>r.forEach((v,x)=>v&&drawCell(x,y,v)));if(now<clearZoomFlashUntil){ctx.globalAlpha=Math.max(0,(clearZoomFlashUntil-now)/110)*.85;ctx.fillStyle='#ffeecc';clearZoomCells.forEach(c=>ctx.fillRect(c.x*CELL+2,c.y*CELL+2,CELL-4,CELL-4));ctx.globalAlpha=1}if(piece&&!gameOver){let gy=piece.y;while(!collides(piece.x,gy+1,piece.m))gy++;piece.m.forEach((r,y)=>r.forEach((v,x)=>{if(v&&gy+y>=0)drawCell(piece.x+x,gy+y,v,.18)}));drawActivePiece()}drawEffects();if(performance.now()<overdriveUntil){ctx.globalAlpha=.08+.04*Math.sin(performance.now()/70);ctx.fillStyle='#ff6973';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.globalAlpha=1}ctx.restore()}
function baseDropInterval(){return Math.max(180,700*Math.pow(.94,currentFloor-1))}
function effectiveDropInterval(){return baseDropInterval()*(1+(buffs.slow||0))*(performance.now()<overdriveUntil?.82:1)*(performance.now()<emergencySlowUntil?2.1:1)}
function currentSpeedMultiplier(){return 700/effectiveDropInterval()}
function drawJesterStatic(preview,pctx){const tick=Math.floor(performance.now()/75),palette=['#46425e','#15788c','#00b9be','#ffeecc','#ffb0a3','#ff6973'];for(let y=0;y<preview.height;y+=4)for(let x=0;x<preview.width;x+=4){const noise=(x*13+y*7+tick*17+(x*y)%19)%palette.length;pctx.fillStyle=palette[noise];pctx.globalAlpha=.35+((noise+tick)%3)*.18;pctx.fillRect(x,y,4,4)}pctx.globalAlpha=1;const band=(tick*7)%preview.height;pctx.fillStyle='#ffeecc';pctx.globalAlpha=.48;pctx.fillRect(0,band,preview.width,3);pctx.fillStyle='#46425e';pctx.fillRect(0,(band+5)%preview.height,preview.width,2);pctx.globalAlpha=1}
function drawPiecePreview(id,type){const preview=document.getElementById(id),pctx=preview.getContext('2d');pctx.clearRect(0,0,preview.width,preview.height);pctx.fillStyle='#46425e';pctx.fillRect(0,0,preview.width,preview.height);if(enemy.kind==='jester'&&enemy.hp>0){drawJesterStatic(preview,pctx);return}if(!type){pctx.fillStyle='#ffb0a3';pctx.font='11px "Ari W9500"';pctx.textAlign='center';pctx.fillText('EMPTY',preview.width/2,preview.height/2+4);return}const m=shapeFor(type),size=isTentacleType(type)?17:22,w=m[0].length*size,h=m.length*size,ox=Math.floor((preview.width-w)/2),oy=Math.floor((preview.height-h)/2);m.forEach((row,y)=>row.forEach((v,x)=>{if(!v)return;const px=ox+x*size,py=oy+y*size;pctx.fillStyle=v===11?'#ff6973':COLORS[v];pctx.fillRect(px+1,py+1,size-2,size-2);pctx.fillStyle='#ffeecc';pctx.fillRect(px+3,py+3,size-6,3);pctx.fillStyle='#46425e';pctx.fillRect(px+4,py+size-4,size-8,2);if(v===11)pctx.fillRect(px+Math.floor(size/2),py+Math.floor(size/2),3,3)}));if(type==='BOMB'){const pulse=Math.floor(performance.now()/90)%2;pctx.fillStyle=pulse?'#ffeecc':'#15788c';pctx.fillRect(preview.width/2-8,preview.height/2-8,16,16);pctx.fillStyle=pulse?'#46425e':'#ffeecc';pctx.fillRect(preview.width/2-3,preview.height/2-3,6,6);pctx.fillStyle='#46425e';pctx.fillRect(preview.width/2+7,preview.height/2-18,4,10)}}
function drawNextPiece(){drawPiecePreview('nextPiece',nextPieceType);drawPiecePreview('nextPiece2',nextPieceType2);drawPiecePreview('holdPiece',hold);drawPiecePreview('holdPiece2',hold2)}
function updateUI(){
 drawNextPiece();
 const obscured=enemy.kind==='jester'&&enemy.hp>0,bombNext=!obscured&&nextPieceType==='BOMB',sealedNext=!obscured&&isSealedType(nextPieceType),tentacleNext=!obscured&&isTentacleType(nextPieceType),bombDistance=piecesUntilBomb+1,nextSlot=document.getElementById('nextSlot');document.getElementById('nextLabel').textContent=obscured?'Signal Lost':bombNext?'Bomb Next':sealedNext?'Sealed Next':tentacleNext?'Impossible':'Next';document.getElementById('bombCounter').textContent=obscured?'QUEUE JAMMED':bombNext?'READY TO DROP':sealedNext?'NO ROTATION':tentacleNext?'ROTATE WITH CARE':`Bomb in ${bombDistance}`;nextSlot.classList.toggle('jester-static',obscured);nextSlot.classList.toggle('bomb-ready',bombNext);nextSlot.classList.toggle('sealed-ready',sealedNext);nextSlot.classList.toggle('bomb-close',!obscured&&!bombNext&&!sealedNext&&!tentacleNext&&bombDistance<=2);
 const stackTop=board.findIndex(row=>row.some(Boolean));document.body.classList.toggle('stack-danger',stackTop>=0&&stackTop<6);if(!emergencyBombTriggered&&stackTop>=0&&stackTop<=4){sfx('emergency');emergencyBombTriggered=true;nextPieceType='BOMB';nextPieceType2='BOMB';forcedBombPieces=1;emergencySlowUntil=performance.now()+2300;floaters.push({text:'LAST CHANCE!  3 BOMBS QUEUED',x:canvas.width/2,y:125,life:2600,max:2600,size:24});const emergency=document.getElementById('emergencyFx');emergency.className='';void emergency.offsetWidth;emergency.className='show';document.body.classList.add('emergency-rescue');transitionAfter(2400,()=>{emergency.className='';document.body.classList.remove('emergency-rescue')});triggerClass(document.getElementById('gamewrap'),'critical-flash')}
 document.getElementById('openWindowSlot').classList.toggle('active',!!buffs.openWindow);document.getElementById('emptyFrameSlot').classList.toggle('active',!!buffs.emptyFrame);document.querySelectorAll('#floorRoute span').forEach((node,i)=>{const step=(currentFloor-1)%5;node.classList.toggle('current',i===step);node.classList.toggle('cleared',i<step)});
 const portrait=document.querySelector('.enemy-portrait');if(portrait.getAttribute('src')!==enemy.portrait)portrait.setAttribute('src',enemy.portrait);
 document.getElementById('enemyName').textContent=enemy.name;
 document.getElementById('attackName').textContent=enemy.attackName;
 document.getElementById('enemyHp').style.width=Math.max(0,enemy.hp/enemy.maxHp*100)+'%';document.getElementById('enemyHpLag').style.width=Math.max(0,enemyHpLagValue/enemy.maxHp*100)+'%';
 document.getElementById('enemyText').textContent=`${Math.max(0,enemy.hp)} / ${enemy.maxHp} HP`;
 const remaining=Math.max(1,enemy.clock-enemy.progress);document.getElementById('attackCountdown').textContent=String(remaining);document.getElementById('attackEffect').textContent=enemy.effect;
 const box=document.querySelector('.enemy-box'),tele=document.getElementById('attackTelegraph');box.classList.remove('kind-goblin','kind-slime','kind-jester','kind-boss');box.classList.add(`kind-${enemy.kind}`);box.classList.toggle('enemy-elite',!!enemy.elite);box.classList.toggle('warning',remaining===2);box.classList.toggle('imminent',remaining===1);tele.classList.toggle('warning',remaining===2);tele.classList.toggle('imminent',remaining===1);
 const stats={hp:playerHp,floor:currentFloor,score:gameScore,damage:attackDamage,armor:playerArmor};Object.entries(stats).forEach(([id,value])=>document.getElementById(id).textContent=String(value));
 document.getElementById('playerHp').style.width=Math.max(0,playerHp)+'%';document.getElementById('playerHpLag').style.width=Math.max(0,playerHpLagValue)+'%';
 document.getElementById('speed').textContent=currentSpeedMultiplier().toFixed(2)+'×';document.getElementById('combo').textContent=comboCount>1?`×${comboCount}`:'—';document.getElementById('overdrive').style.width=(performance.now()<overdriveUntil?100:overdriveMeter)+'%';document.getElementById('overdriveText').textContent=performance.now()<overdriveUntil?`${Math.max(0,(overdriveUntil-performance.now())/1000).toFixed(1)}s`:`${Math.round(overdriveMeter)}%`;document.getElementById('xp').style.width=(currentXp/xpNeed*100)+'%';document.getElementById('xpText').textContent=`Level ${playerLevel} · ${currentXp}/${xpNeed}`;document.getElementById('shards').textContent=String(runShards);document.getElementById('bestFloor').textContent=String(meta.best||0);updateBuffDisplay()
}
function updateBuffDisplay(){const items=[],add=(on,icon,label,detail)=>{if(on){const i=items.length,isBlessing=icon.startsWith('blessing-'),iconMarkup=`<i class="${isBlessing?'blessing-glyph':'hud-icon'} ${icon}" aria-hidden="true"></i>`;items.push(`<span class="buff-chip" tabindex="0" aria-describedby="buff-tip-${i}">${iconMarkup}${label}<span class="buff-tooltip" id="buff-tip-${i}" role="tooltip"><b>${label}</b><p>${detail}</p><small>Active for this run</small></span></span>`)}};add(buffs.combo,'blessing-cascade','Cascade Logic',`Multi-line clears deal extra damage. Current rank: ${buffs.combo||0}.`);add(buffs.execute,'blessing-kill','Kill Switch',`Deal ${Math.round((buffs.execute||0)*100)}% more damage to enemies below half health.`);add(buffs.slow,'blessing-clock','Clock Drag',`Pieces fall ${Math.round((buffs.slow||0)*100)}% slower.`);add(buffs.xp,'blessing-well','Signal Well',`Gain ${Math.round((buffs.xp||0)*100)}% more experience.`);add(buffs.fortify,'blessing-lock','Hard Lock',`Gain ${buffs.fortify||0} bonus armor on periodic locks.`);add(buffs.vampire,'blessing-leech','Leech Circuit',`Heal ${3*(buffs.vampire||0)} HP for every cleared line.`);add(buffs.critical,'blessing-chance','Probability Spike',`${Math.round((buffs.critical||0)*100)}% chance for line damage to be doubled.`);add(buffs.wild,'blessing-spectrum','Spectrum Loop','Every fifth piece grants bonus Fury when locked.');add(buffs.openWindow,'icon-next','Open Window','Reveal a second upcoming piece.');add(buffs.emptyFrame,'icon-hold','Empty Frame','Gain a second Hold slot; C cycles both stored pieces.');const el=document.getElementById('buffs');el.innerHTML=items.join('')||'None yet.';el.querySelectorAll('.buff-chip').forEach(chip=>{const place=()=>{const tip=chip.querySelector('.buff-tooltip'),rect=chip.getBoundingClientRect();tip.style.left=Math.max(10,Math.min(window.innerWidth-270,rect.right+10))+'px';tip.style.top=Math.max(10,Math.min(window.innerHeight-tip.offsetHeight-10,rect.top))+'px'};chip.addEventListener('mouseenter',place);chip.addEventListener('focus',place)})}
const renderBuffDisplay=updateBuffDisplay;updateBuffDisplay=function(){const key=JSON.stringify(buffs);if(updateBuffDisplay.key===key)return;updateBuffDisplay.key=key;renderBuffDisplay()};
function runBuffText(){const a=[];if(buffs.combo)a.push(`Cascade Logic ×${buffs.combo}`);if(buffs.execute)a.push(`Kill Switch ${Math.round(buffs.execute*100)}%`);if(buffs.slow)a.push(`Clock Drag ${Math.round(buffs.slow*100)}%`);if(buffs.xp)a.push(`Signal Well ${Math.round(buffs.xp*100)}%`);if(buffs.fortify)a.push(`Hard Lock +${buffs.fortify}`);if(buffs.vampire)a.push(`Leech Circuit ×${buffs.vampire}`);if(buffs.critical)a.push(`Probability Spike ${Math.round(buffs.critical*100)}%`);if(buffs.wild)a.push('Spectrum Loop');if(buffs.openWindow)a.push('Open Window');if(buffs.emptyFrame)a.push('Empty Frame');return a.join(' · ')}
function loop(t){const dt=Math.min(50,t-last);last=t;updateEffects(t<hitStopUntil?dt*.18:dt);if(!paused&&!gameOver&&t>=hitStopUntil){dropTimer+=dt;const interval=effectiveDropInterval();if(dropTimer>interval){drop();dropTimer=0}}draw();updateUI();requestAnimationFrame(loop)}
function showMessage(title,text,onclose){paused=true;const m=document.getElementById('modal');m.innerHTML=`<h2>${title}</h2><p>${text}</p><button class="big-button" id="continue">Continue</button>`;m.querySelector('#continue').onclick=()=>{hideOverlay();if(onclose)onclose()};showOverlay()}
function startNewRun(){document.body.classList.remove('user-paused','death-summary');document.getElementById('deathSplash').classList.remove('show');document.getElementById('shardFlights').innerHTML='';reset()}
function endRun(){sfx('death');gameOver=true;paused=true;runStats.ended=Date.now();document.body.classList.remove('death-summary');meta.best=Math.max(meta.best||0,currentFloor);saveMeta();const splash=document.getElementById('deathSplash');splash.classList.remove('show');void splash.offsetWidth;splash.classList.add('show');transitionAfter(1450,()=>{const seconds=Math.max(0,Math.floor((runStats.ended-runStats.started)/1000)),time=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;document.body.classList.add('death-summary');const m=document.getElementById('modal');m.innerHTML=`<h2>Run Over</h2><div class="run-summary"><span>Floor reached</span><strong>${currentFloor}</strong><span>Final score</span><strong>${gameScore}</strong><span>Time survived</span><strong>${time}</strong><span>Pieces locked</span><strong>${lockedPieces}</strong><span>Lines cleared</span><strong>${totalLines}</strong><span>Damage dealt</span><strong>${runStats.damage}</strong><span>Damage taken</span><strong>${runStats.damageTaken}</strong><span>Foes defeated</span><strong>${runStats.enemies}</strong><span>Best combo</span><strong>×${runStats.bestCombo}</strong><span>Bombs used</span><strong>${runStats.bombs}</strong><span>Fragments earned</span><strong>${runStats.shardsEarned}</strong><span>Fragments spent</span><strong>${runStats.shardsSpent}</strong></div><p class="small">Unspent fragments (${runShards}) are lost when this run ends. Best Floor is the only persistent record.</p><button class="big-button" id="again">Start New Run</button>`;m.querySelector('#again').onclick=startNewRun;showOverlay()})}
function showOverlay(){document.getElementById('overlay').classList.add('show')}function hideOverlay(){document.getElementById('overlay').classList.remove('show')}
function saveMeta(){localStorage.setItem('blockboundMeta',JSON.stringify({best:meta.best||0}))}function loadMeta(){try{const saved=JSON.parse(localStorage.getItem('blockboundMeta'));return{best:Number(saved&&saved.best)||0}}catch{return{best:0}}}
addEventListener('keydown',e=>{ensureAudio();startMusic();if(gameOver)return;if(['ArrowLeft','ArrowRight','ArrowDown','ArrowUp',' ','z','Z','x','X','c','C','p','P'].includes(e.key))e.preventDefault();if(e.key==='p'||e.key==='P'){if(document.getElementById('overlay').classList.contains('show')||document.getElementById('floorTransition').classList.contains('show'))return;paused=!paused;document.body.classList.toggle('user-paused',paused);return}if(paused)return;if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key==='ArrowDown')drop();if(e.key==='ArrowUp'||e.key==='x'||e.key==='X')rotate(1);if(e.key==='z'||e.key==='Z')rotate(-1);if(e.key===' ')hardDrop();if(e.key==='c'||e.key==='C')doHold()});
document.getElementById('restart').onclick=()=>{ensureAudio();startMusic();startNewRun()};const soundToggle=document.getElementById('soundToggle'),musicToggle=document.getElementById('musicToggle');soundToggle.onclick=()=>{sfxEnabled=!sfxEnabled;soundToggle.setAttribute('aria-pressed',String(sfxEnabled));soundToggle.querySelector('span').textContent=sfxEnabled?'SFX ON':'SFX OFF';soundToggle.classList.toggle('muted',!sfxEnabled);if(sfxEnabled){ensureAudio();tone(440,.06,'square',.025);tone(660,.08,'square',.025,.06)}};musicToggle.onclick=()=>{ensureAudio();startMusic();musicEnabled=!musicEnabled;musicToggle.setAttribute('aria-pressed',String(musicEnabled));musicToggle.querySelector('span').textContent=musicEnabled?'MUSIC ON':'MUSIC OFF';musicToggle.classList.toggle('muted',!musicEnabled)};addEventListener('pointerdown',()=>{ensureAudio();startMusic()},{once:true});pixelateOverdriveLetters();meta=loadMeta();startNewRun();requestAnimationFrame(loop);
})();
